version: '3'

networks:
  mysql8:

services:
  mysql8-service:
    image: mysql:8
    container_name: mysql-go
    ports:
      - "4307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_PASSWORD: 'secret'
    networks:
      - mysql8

